name: Docker Build and Release
on: [ push ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  APP_NAME: "mitchb" #<-- hier wird der Name euer Heroku-App eingetragen
  HEROKU_API_KEY: c100382c-7b72-4ccf-859c-28509b5661c6
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    #### AUFGABE 2: SONAR
      # hier kommt die Konfiguration der Sonar-Analyse rein
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=MichiBaur_pet-clinic



        #### AUFGABE 3 DOCKER BUILD UND PUSH
          # an dieser Stelle wird die Aufgabe 3 bearbeitet: heroku login, docker build, docker push
    - name: Compile, build and push
      run: |
        heroku container:login 
        mvn package
        docker build --tag registry.heroku.com/mitchb/web -f Dockerfile .
        docker push registry.heroku.com/mitchb/web
    - name: Release
      run: |
        heroku container:login 
        heroku stack:set container --app mitchb
        heroku container:release web --app mitchb
        
    - name: Release
      run: |
        #### AUFGABE 4 DEPLOYMENT AUF HEROKU
          # hier wird die 4. Aufgabe bearbeitet: Release der App auf Heroku
        heroku container:login
        heroku stack:set container --app mitchb
        heroku container:release web --app mitchb
